run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gci
    - gofumpt
    - gomnd
    - nlreturn
    - testpackage
    - wsl