run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - funlen
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godot
    - godox
    - gci
    - gocognit
    - gofumpt
    - gomnd
    - ifshort
    - ireturn
    - lll
    - maintidx
    - nestif
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - linters:
        - gocritic
      text: "ifElseChain: rewrite if-else to switch statement"

    - linters:
        - goerr113
      text: "err113: do not define dynamic errors, use wrapped static errors instead:"

    - linters:
        - golint
      text: "`if` block ends with a `return` statement, so drop this `else` and outdent its block"

    - linters:
        - revive
      text: "indent-error-flow: if block ends with a return statement, so drop this else and outdent its block"

    - linters:
        - stylecheck
      text: "ST1005: error strings should not be capitalized"