version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
    - linters: [contextcheck]
      text: "Function `[^`]+` should pass the context parameter"

    - linters: [gocritic]
      text: "ifElseChain: rewrite if-else to switch statement"

    - linters: [goerr113]
      text: "err113: do not define dynamic errors, use wrapped static errors instead:"

    - linters: [golint]
      text: "`if` block ends with a `return` statement, so drop this `else` and outdent its block"

    - linters: [promlinter]
      text: "Error: counter metrics should have \"_total\" suffix"

    - linters: [revive]
      text: "empty-block: this block is empty, you can remove it"

    - linters: [revive]
      text: "indent-error-flow: if block ends with a return statement, so drop this else and outdent its block"

    - linters: [revive]
      text: "unused-parameter: parameter '[^']+' seems to be unused, consider removing or renaming it as _"

    - linters: [staticcheck, stylecheck]
      text: "ST1005: error strings should not be capitalized"