run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gci
    - gocognit
    - gofumpt
    - gomnd
    - ifshort
    - lll
    - nestif
    - nlreturn
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl