#!/usr/bin/env bash

set -eu

go mod tidy

src_dirs="$(realpath --no-symlinks --relative-to "$PWD" $(go list -f '{{.Dir}}' ./...))"
docker run --rm -v "$PWD:/data" cytopia/gofmt -s -w $src_dirs
docker run --rm -v "$PWD:/data" cytopia/goimports -local github.com/KonishchevDmitry/server-metrics -w $src_dirs

./run