#!/usr/bin/env bash

set -eu

name=server-metrics
full_name=konishchev/$name

DOCKER_BUILDKIT=1 docker build --pull --tag "$full_name:stable" .

docker stop "$name" > /dev/null ||:
docker rm "$name" > /dev/null ||:
docker run --pid host --read-only --detach --publish 127.0.0.1:9101:9101 --restart unless-stopped \
    --mount type=bind,src=/dev,dst=/dev,readonly \
    --mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly \
    --name "$name" --log-opt "tag=$name" "$full_name:stable" > /dev/null