#!/usr/bin/env bash

set -eu
export DOCKER_CONTEXT=server

name=server-metrics
full_name=konishchev/$name

docker build --pull --tag "$full_name:stable" .

if docker inspect "$name" > /dev/null 2>&1; then
    docker stop "$name" > /dev/null
    docker rm "$name" > /dev/null
fi

docker run --detach --restart unless-stopped \
    --pid host --network host --read-only \
    --cap-drop all --cap-add NET_ADMIN --cap-add CAP_SYSLOG --security-opt no-new-privileges \
    --device /dev/kmsg:/dev/kmsg \
    --mount type=bind,src=/dev,dst=/dev,readonly \
    --mount type=bind,src=/sys,dst=/sys,readonly \
    --mount type=bind,src=/etc/passwd,dst=/etc/passwd,readonly \
    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src=/run/podman/podman.sock,dst=/run/podman/podman.sock \
    --mount type=bind,src=/run/systemd/journal/socket,dst=/run/systemd/journal/socket \
    --name "$name" --log-opt "tag=$name" "$full_name:stable" > /dev/null

ssh -t root@server.lan '
    set -eu

    curl -s http://localhost:9101/metrics | sed -r "
        /^#/ d
        s/^(.+) [^ ]+\$/\1/
        /^server_memory_meminfo/!s/^([^{ ]+).*\$/\1/
    " | sort -u > /etc/monitoring/metrics-server.dump

    cd /etc/monitoring && git diff metrics-server.dump >&2
'